# Generated by Django 5.1.4 on 2026-05-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RcEvent',
            fields=[
                ('event_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('app_user_id', models.CharField(db_index=True, max_length=200)),
                ('product_id', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('is_trial_conversion', models.BooleanField(default=False)),
                ('is_renewal', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AsaDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('campaign_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=2)),
                ('search_term', models.CharField(blank=True, max_length=500)),
                ('keyword', models.CharField(max_length=200)),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact'), ('BROAD', 'Broad'), ('SEARCH_MATCH', 'Search Match')], max_length=20)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impressions', models.IntegerField(default=0)),
                ('taps', models.IntegerField(default=0)),
                ('installs', models.IntegerField(default=0)),
                ('ttr', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('cpt', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cpa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'campaign_name', 'country', 'search_term', 'keyword', 'match_type')},
            },
        ),
        migrations.CreateModel(
            name='Ga4DailyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('app_version', models.CharField(max_length=20)),
                ('traffic_source', models.CharField(blank=True, max_length=50, null=True)),
                ('event_count', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'event_name', 'country', 'app_version', 'traffic_source')},
            },
        ),
        migrations.CreateModel(
            name='Ga4DailyFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('app_version', models.CharField(blank=True, max_length=20, null=True)),
                ('first_open', models.IntegerField(default=0)),
                ('onboarding_completed', models.IntegerField(default=0)),
                ('recording_started', models.IntegerField(default=0)),
                ('recording_completed', models.IntegerField(default=0)),
                ('paywall_shown', models.IntegerField(default=0)),
                ('purchase_initiated', models.IntegerField(default=0)),
                ('purchase_succeeded', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'country', 'app_version')},
            },
        ),
        migrations.CreateModel(
            name='RcSubscriptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('app_user_id', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('product_id', models.CharField(blank=True, max_length=200, null=True)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('in_grace_period', 'In Grace Period'), ('none', 'None')], max_length=50)),
                ('mrr_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_today_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_discounted', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('snapshot_date', 'app_user_id')},
            },
        ),
    ]
