# Generated by Django 5.1.4 on 2026-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asadailymetrics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asadailymetrics',
            name='installs_tap_through',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asadailymetrics',
            name='installs_view_through',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asadailymetrics',
            name='level',
            field=models.CharField(choices=[('campaign', 'Campaign'), ('ad_group', 'Ad Group'), ('keyword', 'Keyword'), ('search_term', 'Search Term')], default='campaign', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asadailymetrics',
            name='new_downloads_tap_through',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asadailymetrics',
            name='new_downloads_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asadailymetrics',
            name='new_downloads_view_through',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asadailymetrics',
            name='redownloads_tap_through',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asadailymetrics',
            name='redownloads_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asadailymetrics',
            name='redownloads_view_through',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asadailymetrics',
            name='keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asadailymetrics',
            name='match_type',
            field=models.CharField(blank=True, choices=[('EXACT', 'Exact'), ('BROAD', 'Broad'), ('SEARCH_MATCH', 'Search Match')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='asadailymetrics',
            unique_together={('date', 'level', 'campaign_name', 'country', 'search_term', 'keyword', 'match_type')},
        ),
    ]
