# Generated by Django 5.1.4 on 2026-05-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_asadailymetrics_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RcActiveSubscriber',
            fields=[
                ('app_user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=100)),
                ('app_id', models.CharField(max_length=50)),
                ('app_name', models.CharField(max_length=100)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('first_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('trial_start_at', models.DateTimeField(blank=True, null=True)),
                ('trial_end_at', models.DateTimeField(blank=True, null=True)),
                ('most_recent_purchase_at', models.DateTimeField(blank=True, null=True)),
                ('most_recent_renewal_at', models.DateTimeField(blank=True, null=True)),
                ('latest_expiration_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_opt_out_at', models.DateTimeField(blank=True, null=True)),
                ('trial_opt_out_at', models.DateTimeField(blank=True, null=True)),
                ('most_recent_billing_issues_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_app_version', models.CharField(blank=True, max_length=20)),
                ('last_seen_ip_country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('last_seen_platform', models.CharField(blank=True, max_length=20)),
                ('last_seen_platform_version', models.CharField(blank=True, max_length=200)),
                ('last_seen_sdk_version', models.CharField(blank=True, max_length=20)),
                ('last_seen_locale', models.CharField(blank=True, max_length=100)),
                ('media_source', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=200)),
                ('ad_group', models.CharField(blank=True, max_length=200)),
                ('ad', models.CharField(blank=True, max_length=200)),
                ('keyword', models.CharField(blank=True, max_length=200)),
                ('creative', models.CharField(blank=True, max_length=200)),
                ('latest_entitlement', models.CharField(blank=True, max_length=50)),
                ('latest_entitlements', models.CharField(blank=True, max_length=200)),
                ('latest_product', models.CharField(blank=True, db_index=True, max_length=100)),
                ('all_purchased_product_ids', models.TextField(blank=True)),
                ('is_rc_promo', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, db_index=True, max_length=30)),
                ('total_renewals', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('latest_store', models.CharField(blank=True, max_length=30)),
                ('latest_store_country', models.CharField(blank=True, max_length=2)),
                ('latest_auto_renew_intent', models.BooleanField(blank=True, null=True)),
                ('latest_offer', models.CharField(blank=True, max_length=200)),
                ('latest_offer_type', models.CharField(blank=True, max_length=50)),
                ('latest_purchased_offering', models.CharField(blank=True, max_length=100)),
                ('latest_ownership_type', models.CharField(blank=True, max_length=30)),
                ('has_made_sandbox_purchase', models.BooleanField(default=False)),
                ('has_made_a_non_subscription_purchase', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('price_experiment_id', models.CharField(blank=True, max_length=50)),
                ('price_experiment_variant', models.CharField(blank=True, max_length=50)),
                ('custom_attributes', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.CharField(blank=True, help_text='Filename of the import source', max_length=200)),
            ],
            options={
                'ordering': ['-first_purchase_at'],
                'indexes': [models.Index(fields=['status', 'latest_product'], name='analytics_r_status_bd2d7f_idx'), models.Index(fields=['last_seen_ip_country', 'status'], name='analytics_r_last_se_c0dcf8_idx'), models.Index(fields=['first_purchase_at'], name='analytics_r_first_p_0e11e4_idx')],
            },
        ),
    ]
