# Generated by Django 5.1.4 on 2026-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user_id', models.CharField(db_index=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(choices=[('optimize', 'Optimize'), ('split', 'Split')], max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('upstream_error', 'Upstream error'), ('rejected', 'Rejected')], max_length=20)),
                ('reject_reason', models.CharField(blank=True, max_length=50)),
                ('input_chars', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntitlementCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField()),
            ],
        ),
    ]
