# Generated by Django 5.1.4 on 2026-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITextLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(choices=[('optimize', 'Optimize'), ('split', 'Split')], max_length=20)),
                ('is_paid', models.BooleanField()),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('accept_language', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
